import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TopNav } from "./_components/topnav";

export const metadata: Metadata = {
  title: "T3 Gallery ",
  description: "Generated by pratham srivastava",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// function TopNav() {
//   return (
//     <nav className="flex w-full items-center justify-between border-b p-4 text-xl font-semibold">
//       <div>Gallary</div>
//       <div>Sign In</div>
//     </nav>
//   );
// }
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className={`flex flex-col gap-4 font-sans`}>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
